# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('detail_time', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('url', models.URLField()),
                ('source', models.CharField(max_length=50)),
                ('web', models.CharField(max_length=50)),
                ('logtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
